SELECT CAST(CASE WHEN COUNT(PG.IDENT) > 0 THEN 1 ELSE 0 END AS BIT) IsPago 
 FROM TB_PAGAMENTO PG   
 JOIN TB_PAGAMENTO_CABECALHO PAG ON PAG.IDENT = PG.ID_PAGAMENTO_CABECALHO   
 JOIN TB_PAGAMENTO_CABECALHO_OCORRENCIA PAG_OCOR ON PAG_OCOR.ID_PAGAMENTO_CABECALHO = PAG.IDENT   
JOIN TB_OCORRENCIA OCOR ON OCOR.IDENT = PAG_OCOR.ID_OCORRENCIA   
 WHERE OCOR.IDENT = 1234 
 AND PG.ID_STATUS = 100
